-- apply changes
create table users (
  id                            bigint generated by default as identity not null,
  role                          integer not null,
  username                      varchar not null,
  email_address                 varchar not null,
  hashed_password               varchar,
  google_id                     varchar,
  constraint ck_users_role check ( role in (0,1)),
  constraint uq_users_username unique (username),
  constraint uq_users_email_address unique (email_address),
  constraint pk_users primary key (id)
);

