-- apply changes
create table categories (
  id                            bigint generated by default as identity not null,
  user_id                       bigint not null,
  name                          varchar not null,
  constraint pk_categories primary key (id)
);

create table expenses (
  id                            bigint generated by default as identity not null,
  user_id                       bigint not null,
  category_id                   bigint,
  date                          date not null,
  amount                        decimal(15,2) not null,
  label                         varchar not null,
  currency                      varchar not null,
  constraint pk_expenses primary key (id)
);

create table users (
  id                            bigint generated by default as identity not null,
  role                          integer not null,
  username                      varchar not null,
  email_address                 varchar not null,
  hashed_password               varchar,
  google_id                     varchar,
  constraint ck_users_role check ( role in (0,1)),
  constraint uq_users_username unique (username),
  constraint uq_users_email_address unique (email_address),
  constraint pk_users primary key (id)
);

-- foreign keys and indices
create index ix_categories_user_id on categories (user_id);
alter table categories add constraint fk_categories_user_id foreign key (user_id) references users (id) on delete restrict on update restrict;

create index ix_expenses_user_id on expenses (user_id);
alter table expenses add constraint fk_expenses_user_id foreign key (user_id) references users (id) on delete restrict on update restrict;

create index ix_expenses_category_id on expenses (category_id);
alter table expenses add constraint fk_expenses_category_id foreign key (category_id) references categories (id) on delete restrict on update restrict;

