apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: expenses-tracker-backend
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
spec:
  tls:
    - hosts:
        - "moneymind.fyi"
      secretName: bankable-tls
  rules:
    - host: moneymind.fyi
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: expenses-tracker-backend
                port:
                  number: 9000
