import {FontAwesome6, MaterialCommunityIcons} from "@expo/vector-icons";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import FontAwesome5 from "@expo/vector-icons/FontAwesome5";

export const icons = Object.freeze({
    house: 'house',
    groceries: 'groceries',
    video_games: 'sports-esports',
    school: 'school',
    restaurant: 'fastfood',
    car: 'directions-car',
    baby: 'child-friendly',
    plane: 'airplane',
    trip: 'island',
    bus: 'bus',
    road: 'road',
    oil: 'gas-pump',
    train: 'train',
    clothes: 'clothes',
    gift: 'gift',
    beer: 'beer',
    electricity: 'electricity',
    fire: 'fire',
    water: 'water',
    umbrella: 'umbrella',
    wifi: 'wifi',
    sim: 'sim',
    play: 'play',
    work: 'briefcase',
    coffee: 'coffee',
    rocket: 'rocket',
    bread: 'bread',
    sofa: 'sofa',
    phone: 'phone',
    music: 'music',
    book: 'book',
    trend_up: 'trend_up',
    friends: 'friends',
    mobile: 'mobile',
    bank: 'bank',
    cocktail: 'cocktail',
    scissors: 'scissors',
    pill: 'pill',
    unknown: 'unknown',
})