-- apply changes
create table month_commentaries (
  id                            bigint generated by default as identity not null,
  month                         integer not null,
  year                          integer not null,
  user_id                       bigint not null,
  comment                       varchar not null,
  constraint pk_month_commentaries primary key (id)
);

-- apply alter tables
alter table expenses add column if not exists hidden boolean default false not null;
alter table expenses add column if not exists marked boolean default false not null;
-- foreign keys and indices
create index ix_month_commentaries_user_id on month_commentaries (user_id);
alter table month_commentaries add constraint fk_month_commentaries_user_id foreign key (user_id) references users (id) on delete restrict on update restrict;

