-- apply changes
create table expense_tag (
  expense_id                    bigint not null,
  tag_id                        bigint not null,
  constraint pk_expense_tag primary key (expense_id,tag_id)
);

create table tags (
  id                            bigint generated by default as identity not null,
  user_id                       bigint not null,
  label                         varchar not null,
  constraint pk_tags primary key (id)
);

-- foreign keys and indices
create index ix_expense_tag_expenses on expense_tag (expense_id);
alter table expense_tag add constraint fk_expense_tag_expenses foreign key (expense_id) references expenses (id) on delete restrict on update restrict;

create index ix_expense_tag_tags on expense_tag (tag_id);
alter table expense_tag add constraint fk_expense_tag_tags foreign key (tag_id) references tags (id) on delete restrict on update restrict;

create index ix_tags_user_id on tags (user_id);
alter table tags add constraint fk_tags_user_id foreign key (user_id) references users (id) on delete restrict on update restrict;

