-- apply changes
create table recurring_expenses (
  id                            bigint generated by default as identity not null,
  user_id                       bigint not null,
  category_id                   bigint,
  day_of_month                  integer not null,
  next_date                     date not null,
  last_generated_date           date,
  amount                        decimal(15,2) not null,
  title                         varchar not null,
  currency                      varchar not null,
  type                          varchar(7) not null,
  constraint ck_recurring_expenses_type check ( type in ('EXPENSE','INCOME')),
  constraint pk_recurring_expenses primary key (id)
);

create table recurring_expense_tag (
  recurring_expense_id          bigint not null,
  tag_id                        bigint not null,
  constraint pk_recurring_expense_tag primary key (recurring_expense_id,tag_id)
);

-- foreign keys and indices
create index ix_recurring_expenses_user_id on recurring_expenses (user_id);
alter table recurring_expenses add constraint fk_recurring_expenses_user_id foreign key (user_id) references users (id) on delete restrict on update restrict;

create index ix_recurring_expenses_category_id on recurring_expenses (category_id);
alter table recurring_expenses add constraint fk_recurring_expenses_category_id foreign key (category_id) references subcategories (id) on delete restrict on update restrict;

create index ix_recurring_expense_tag_recurring_expenses on recurring_expense_tag (recurring_expense_id);
alter table recurring_expense_tag add constraint fk_recurring_expense_tag_recurring_expenses foreign key (recurring_expense_id) references recurring_expenses (id) on delete restrict on update restrict;

create index ix_recurring_expense_tag_tags on recurring_expense_tag (tag_id);
alter table recurring_expense_tag add constraint fk_recurring_expense_tag_tags foreign key (tag_id) references tags (id) on delete restrict on update restrict;

