-- apply changes
create table api_keys (
  id                            bigint generated by default as identity not null,
  user_id                       bigint not null,
  created_at                    date not null,
  last_used_at                  date,
  name                          varchar not null,
  hashed_key                    varchar not null,
  hint                          varchar not null,
  constraint uq_api_keys_hashed_key unique (hashed_key),
  constraint pk_api_keys primary key (id)
);

-- foreign keys and indices
create index ix_api_keys_user_id on api_keys (user_id);
alter table api_keys add constraint fk_api_keys_user_id foreign key (user_id) references users (id) on delete restrict on update restrict;

