-- drop dependencies
alter table if exists expenses drop constraint if exists fk_expenses_category_id;
alter table users drop constraint if exists ck_users_role;
-- apply changes
create table subcategories (
  id                            bigint generated by default as identity not null,
  user_id                       bigint not null,
  is_default                    boolean default false not null,
  parent_category_id            bigint not null,
  name                          varchar not null,
  icon                          varchar not null,
  type                          varchar(7) not null,
  constraint ck_subcategories_type check ( type in ('EXPENSE','INCOME')),
  constraint pk_subcategories primary key (id)
);

-- apply alter tables
alter table categories add column if not exists color varchar default '#ffffff' not null;
alter table categories add column if not exists icon varchar default '' not null;
alter table categories add column if not exists type varchar(7) default 'EXPENSE' not null;
alter table expenses add column if not exists type varchar(7) default 'EXPENSE' not null;
alter table users alter column role type varchar(5) using role::varchar(5);
-- apply post alter
alter table categories add constraint ck_categories_type check ( type in ('EXPENSE','INCOME'));
alter table expenses add constraint ck_expenses_type check ( type in ('EXPENSE','INCOME'));
alter table users add constraint ck_users_role check ( role in ('USER','ADMIN'));
-- foreign keys and indices
create index ix_subcategories_user_id on subcategories (user_id);
alter table subcategories add constraint fk_subcategories_user_id foreign key (user_id) references users (id) on delete restrict on update restrict;

create index ix_subcategories_parent_category_id on subcategories (parent_category_id);
alter table subcategories add constraint fk_subcategories_parent_category_id foreign key (parent_category_id) references categories (id) on delete restrict on update restrict;

alter table expenses add constraint fk_expenses_category_id foreign key (category_id) references subcategories (id) on delete restrict on update restrict;
