-- drop dependencies
alter table users drop constraint uq_users_username;
-- apply changes
create table account_reports (
  id                            bigint generated by default as identity not null,
  account_id                    bigint not null,
  date                          date not null,
  amount                        decimal(15,2) not null,
  constraint pk_account_reports primary key (id)
);

create table investments (
  id                            bigint generated by default as identity not null,
  account_id                    bigint not null,
  user_id                       bigint not null,
  date                          date not null,
  amount                        decimal(15,2) not null,
  type                          varchar(3) default 'EXPENSE' not null,
  constraint ck_investments_type check ( type in ('IN','OUT')),
  constraint pk_investments primary key (id)
);

create table investment_accounts (
  id                            bigint generated by default as identity not null,
  owner_id                      bigint not null,
  name                          varchar not null,
  constraint uq_investment_accounts_owner_id unique (owner_id),
  constraint pk_investment_accounts primary key (id)
);

-- foreign keys and indices
create index ix_account_reports_account_id on account_reports (account_id);
alter table account_reports add constraint fk_account_reports_account_id foreign key (account_id) references investment_accounts (id) on delete restrict on update restrict;

create index ix_investments_account_id on investments (account_id);
alter table investments add constraint fk_investments_account_id foreign key (account_id) references investment_accounts (id) on delete restrict on update restrict;

create index ix_investments_user_id on investments (user_id);
alter table investments add constraint fk_investments_user_id foreign key (user_id) references users (id) on delete restrict on update restrict;

alter table investment_accounts add constraint fk_investment_accounts_owner_id foreign key (owner_id) references users (id) on delete restrict on update restrict;

